// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uztaivbsrtalpjvsgyyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6dGFpdmJzcnRhbHBqdnNneXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Njk2MTMsImV4cCI6MjA3MDU0NTYxM30.spCTIe_hCTXiw6POGuzXfe9OXutdZHEHAPJp-2nm65s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});